version: '3.4'

services:
  jupyterlab:
    image: sensorium
    container_name: ditial_twin_course    
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
      - ./data:/notebooks/data
      - ./vscode-server:/root/.vscode-server
    environment:
      - JUPYTER_PASSWORD=aslkdjasdkas
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['7']
            capabilities: [gpu]
