version: '3.4'

services:
  dev:
    image: sensorium
    container_name: postsub_training 
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
      - ./data:/notebooks/data
      - ./vscode-server:/root/.vscode-server
    #environment:
    #  - JUPYTER_PASSWORD=aslkdjasdkas
    #env_file:
    #  - ./.env
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['7']
    #         capabilities: [gpu]
    entrypoint: /bin/bash -c "sleep infinity"
